name: Sync IPTV List
on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上8点运行
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: results # 确保始终在 results 分支操作

      - name: Download m3u
        run: |
          # 使用 curl 下载原始地址的 m3u 文件
          curl -L https://iptv-org.github.io/iptv/index.m3u -o index.m3u

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 如果文件有变动则提交，没有变动则跳过
          if [ -n "$(git status --porcelain)" ]; then
            git add index.m3u
            git commit -m "Update index.m3u $(date +'%Y-%m-%d')"
            git push origin results
          else
            echo "No changes detected."
          fi
